// Curated semantic content (design doc Section 6.2, Open Question 14.1).
// CORE_LIST is the always-included baseline — a Swadesh list extended well
// past basic vocabulary into emotions, abstract concepts, social roles,
// basic technology, and common objects, per Section 6.2's explicit scope.
// FLEXIBLE_LIST holds culture-flavor domains (nautical, agricultural, ...)
// that a user weights to spend the remaining ~50-slot budget on vocabulary
// implying something about the language's (fictional) speakers.
// COMPOUND_LIST is the curated set of non-literal/idiomatic formations
// (Section 6.3) — each references two ids from CORE_LIST/FLEXIBLE_LIST.

import type { CompoundConcept, CoreConcept, FlexibleConcept, FlexibleDomain, FrequencyTier, PartOfSpeech } from "./types";

type Tuple = [id: string, gloss: string, pos: PartOfSpeech];

/** Default frequency tier per CORE_LIST category (Frequency-weighted root complexity patch). */
const CATEGORY_DEFAULT_TIER: Record<string, FrequencyTier> = {
  grammar: "A",
  colors_numbers: "B",
  actions: "B",
  body: "B",
  qualities: "B",
  people: "C",
  nature: "C",
  time: "C",
  animals: "C",
  emotion_abstract: "D",
  social: "D",
  objects: "D",
};

/** Named per-concept overrides of the category default (Frequency-weighted root complexity patch). */
const TIER_EXCEPTIONS: Record<string, FrequencyTier> = {
  one: "A",
  two: "A",
  three: "A",
  four: "A",
  five: "A",
  be: "A",
  have: "A",
  do: "A",
  go: "A",
  see: "A",
  say: "A",
  big: "A",
  small: "A",
  good: "A",
  bad: "A",
  mother: "B",
  father: "B",
  child: "B",
};

function core(category: string, items: Tuple[]): CoreConcept[] {
  const defaultTier = CATEGORY_DEFAULT_TIER[category];
  if (!defaultTier) throw new Error(`core(): no CATEGORY_DEFAULT_TIER entry for category "${category}"`);
  return items.map(([id, gloss, pos]) => ({
    id,
    gloss,
    pos,
    category,
    frequencyTier: TIER_EXCEPTIONS[id] ?? defaultTier,
  }));
}

function flexible(domain: FlexibleDomain, items: Tuple[]): FlexibleConcept[] {
  return items.map(([id, gloss, pos]) => ({ id, gloss, pos, domain }));
}

export const CORE_LIST: CoreConcept[] = [
  ...core("grammar", [
    ["i", "I", "pronoun"],
    ["you_sg", "you (sg.)", "pronoun"],
    ["he_she_it", "he/she/it", "pronoun"],
    ["we", "we", "pronoun"],
    ["you_pl", "you (pl.)", "pronoun"],
    ["they", "they", "pronoun"],
    ["this", "this", "pronoun"],
    ["that", "that", "pronoun"],
    ["who", "who", "pronoun"],
    ["what", "what", "pronoun"],
    ["where", "where", "adverb"],
    ["when", "when", "adverb"],
    ["why", "why", "adverb"],
    ["how", "how", "adverb"],
    ["not", "not", "function"],
    ["and", "and", "function"],
    ["or", "or", "function"],
    ["but", "but", "function"],
    ["if", "if", "function"],
    ["because", "because", "function"],
    ["all", "all", "function"],
    ["some", "some", "function"],
    ["many", "many", "adjective"],
    ["few", "few", "adjective"],
    ["other", "other", "adjective"],
  ]),
  ...core("nature", [
    ["sun", "sun", "noun"],
    ["moon", "moon", "noun"],
    ["star", "star", "noun"],
    ["sky", "sky", "noun"],
    ["cloud", "cloud", "noun"],
    ["rain", "rain", "noun"],
    ["snow", "snow", "noun"],
    ["wind", "wind", "noun"],
    ["fire", "fire", "noun"],
    ["water", "water", "noun"],
    ["earth", "earth, soil", "noun"],
    ["stone", "stone", "noun"],
    ["sand", "sand", "noun"],
    ["mountain", "mountain", "noun"],
    ["hill", "hill", "noun"],
    ["valley", "valley", "noun"],
    ["river", "river", "noun"],
    ["lake", "lake", "noun"],
    ["sea", "sea", "noun"],
    ["forest", "forest", "noun"],
    ["tree", "tree", "noun"],
    ["leaf", "leaf", "noun"],
    ["root_plant", "root (of a plant)", "noun"],
    ["flower", "flower", "noun"],
    ["grass", "grass", "noun"],
    ["seed", "seed", "noun"],
    ["fruit", "fruit", "noun"],
    ["wood", "wood", "noun"],
    ["ash", "ash", "noun"],
    ["smoke", "smoke", "noun"],
    ["ice", "ice", "noun"],
    ["fog", "fog", "noun"],
    ["thunder", "thunder", "noun"],
    ["lightning", "lightning", "noun"],
    ["rainbow", "rainbow", "noun"],
    ["shadow", "shadow", "noun"],
    ["light", "light (illumination)", "noun"],
    ["dark", "dark", "adjective"],
    ["day", "day", "noun"],
    ["night", "night", "noun"],
    ["salt", "salt", "noun"],
  ]),
  ...core("time", [
    ["year", "year", "noun"],
    ["month", "month", "noun"],
    ["week", "week", "noun"],
    ["hour", "hour", "noun"],
    ["morning", "morning", "noun"],
    ["noon", "noon", "noun"],
    ["evening", "evening", "noun"],
    ["today", "today", "adverb"],
    ["yesterday", "yesterday", "adverb"],
    ["tomorrow", "tomorrow", "adverb"],
    ["season", "season", "noun"],
    ["spring", "spring", "noun"],
    ["summer", "summer", "noun"],
    ["autumn", "autumn", "noun"],
    ["winter", "winter", "noun"],
  ]),
  ...core("body", [
    ["head", "head", "noun"],
    ["hair", "hair", "noun"],
    ["face", "face", "noun"],
    ["eye", "eye", "noun"],
    ["ear", "ear", "noun"],
    ["nose", "nose", "noun"],
    ["mouth", "mouth", "noun"],
    ["tooth", "tooth", "noun"],
    ["tongue", "tongue", "noun"],
    ["neck", "neck", "noun"],
    ["shoulder", "shoulder", "noun"],
    ["arm", "arm", "noun"],
    ["hand", "hand", "noun"],
    ["finger", "finger", "noun"],
    ["nail", "nail (finger)", "noun"],
    ["chest", "chest", "noun"],
    ["belly", "belly", "noun"],
    ["back_body", "back (body)", "noun"],
    ["leg", "leg", "noun"],
    ["foot", "foot", "noun"],
    ["knee", "knee", "noun"],
    ["skin", "skin", "noun"],
    ["bone", "bone", "noun"],
    ["blood", "blood", "noun"],
    ["heart", "heart", "noun"],
    ["liver", "liver", "noun"],
    ["lung", "lung", "noun"],
    ["brain", "brain", "noun"],
    ["breath", "breath", "noun"],
    ["voice", "voice", "noun"],
    ["sweat", "sweat", "noun"],
    ["tear_body", "tear (crying)", "noun"],
    ["saliva", "saliva", "noun"],
    ["milk", "milk", "noun"],
    ["egg", "egg", "noun"],
  ]),
  ...core("people", [
    ["person", "person", "noun"],
    ["man", "man", "noun"],
    ["woman", "woman", "noun"],
    ["child", "child", "noun"],
    ["baby", "baby", "noun"],
    ["elder", "elder", "noun"],
    ["mother", "mother", "noun"],
    ["father", "father", "noun"],
    ["sister", "sister", "noun"],
    ["brother", "brother", "noun"],
    ["son", "son", "noun"],
    ["daughter", "daughter", "noun"],
    ["husband", "husband", "noun"],
    ["wife", "wife", "noun"],
    ["friend", "friend", "noun"],
    ["stranger", "stranger", "noun"],
    ["enemy", "enemy", "noun"],
    ["leader", "leader", "noun"],
    ["chief", "chief", "noun"],
    ["healer", "healer", "noun"],
    ["teacher", "teacher", "noun"],
    ["student", "student", "noun"],
    ["warrior", "warrior", "noun"],
    ["farmer", "farmer", "noun"],
    ["hunter", "hunter", "noun"],
    ["trader", "trader", "noun"],
    ["priest", "priest", "noun"],
    ["king", "king", "noun"],
    ["queen", "queen", "noun"],
    ["servant", "servant", "noun"],
    ["guest", "guest", "noun"],
    ["neighbor", "neighbor", "noun"],
    ["ancestor", "ancestor", "noun"],
    ["name", "name", "noun"],
    ["people", "people (a folk)", "noun"],
  ]),
  ...core("animals", [
    ["animal", "animal", "noun"],
    ["bird", "bird", "noun"],
    ["dog", "dog", "noun"],
    ["cat", "cat", "noun"],
    ["fish", "fish", "noun"],
    ["snake", "snake", "noun"],
    ["wolf", "wolf", "noun"],
    ["bear", "bear", "noun"],
    ["deer", "deer", "noun"],
    ["rabbit", "rabbit", "noun"],
    ["mouse", "mouse", "noun"],
    ["horse", "horse", "noun"],
    ["cow", "cow", "noun"],
    ["sheep", "sheep", "noun"],
    ["goat", "goat", "noun"],
    ["pig", "pig", "noun"],
    ["chicken", "chicken", "noun"],
    ["insect", "insect", "noun"],
    ["bee", "bee", "noun"],
    ["spider", "spider", "noun"],
    ["ant", "ant", "noun"],
    ["butterfly", "butterfly", "noun"],
    ["frog", "frog", "noun"],
    ["turtle", "turtle", "noun"],
    ["owl", "owl", "noun"],
    ["eagle", "eagle", "noun"],
    ["crow", "crow", "noun"],
    ["fox", "fox", "noun"],
    ["lion", "lion", "noun"],
    ["mosquito", "mosquito", "noun"],
  ]),
  ...core("actions", [
    ["be", "be", "verb"],
    ["have", "have", "verb"],
    ["do", "do", "verb"],
    ["go", "go", "verb"],
    ["come", "come", "verb"],
    ["walk", "walk", "verb"],
    ["run", "run", "verb"],
    ["jump", "jump", "verb"],
    ["fly", "fly", "verb"],
    ["swim", "swim", "verb"],
    ["sit", "sit", "verb"],
    ["stand", "stand", "verb"],
    ["lie_down", "lie down", "verb"],
    ["sleep", "sleep", "verb"],
    ["wake", "wake", "verb"],
    ["eat", "eat", "verb"],
    ["drink", "drink", "verb"],
    ["bite", "bite", "verb"],
    ["chew", "chew", "verb"],
    ["see", "see", "verb"],
    ["hear", "hear", "verb"],
    ["smell", "smell", "verb"],
    ["taste", "taste", "verb"],
    ["touch", "touch", "verb"],
    ["speak", "speak", "verb"],
    ["say", "say", "verb"],
    ["tell", "tell", "verb"],
    ["ask", "ask", "verb"],
    ["answer", "answer", "verb"],
    ["know", "know", "verb"],
    ["think", "think", "verb"],
    ["believe", "believe", "verb"],
    ["remember", "remember", "verb"],
    ["forget", "forget", "verb"],
    ["learn", "learn", "verb"],
    ["teach", "teach", "verb"],
    ["understand", "understand", "verb"],
    ["want", "want", "verb"],
    ["need", "need", "verb"],
    ["like", "like", "verb"],
    ["love", "love", "verb"],
    ["hate", "hate", "verb"],
    ["fear_verb", "fear (verb)", "verb"],
    ["hope_verb", "hope (verb)", "verb"],
    ["laugh", "laugh", "verb"],
    ["cry", "cry", "verb"],
    ["smile", "smile", "verb"],
    ["sing", "sing", "verb"],
    ["dance", "dance", "verb"],
    ["play", "play", "verb"],
    ["work", "work", "verb"],
    ["rest", "rest", "verb"],
    ["help", "help", "verb"],
    ["give", "give", "verb"],
    ["take", "take", "verb"],
    ["hold", "hold", "verb"],
    ["carry", "carry", "verb"],
    ["throw", "throw", "verb"],
    ["catch", "catch", "verb"],
    ["push", "push", "verb"],
    ["pull", "pull", "verb"],
    ["cut", "cut", "verb"],
    ["break", "break", "verb"],
    ["build", "build", "verb"],
    ["make", "make", "verb"],
    ["burn", "burn", "verb"],
    ["kill", "kill", "verb"],
    ["die", "die", "verb"],
    ["live", "live", "verb"],
    ["grow", "grow", "verb"],
    ["change", "change", "verb"],
    ["begin", "begin", "verb"],
    ["end", "end", "verb"],
    ["wait", "wait", "verb"],
    ["hide_verb", "hide (verb)", "verb"],
    ["find", "find", "verb"],
    ["lose", "lose", "verb"],
    ["win", "win", "verb"],
    ["fight", "fight", "verb"],
    ["buy", "buy", "verb"],
    ["sell", "sell", "verb"],
    ["count_verb", "count (verb)", "verb"],
  ]),
  ...core("qualities", [
    ["big", "big", "adjective"],
    ["small", "small", "adjective"],
    ["long", "long", "adjective"],
    ["short", "short", "adjective"],
    ["wide", "wide", "adjective"],
    ["narrow", "narrow", "adjective"],
    ["tall", "tall", "adjective"],
    ["deep", "deep", "adjective"],
    ["shallow", "shallow", "adjective"],
    ["heavy", "heavy", "adjective"],
    ["light_weight", "light (not heavy)", "adjective"],
    ["fast", "fast", "adjective"],
    ["slow", "slow", "adjective"],
    ["hot", "hot", "adjective"],
    ["cold", "cold", "adjective"],
    ["warm", "warm", "adjective"],
    ["cool", "cool", "adjective"],
    ["wet", "wet", "adjective"],
    ["dry", "dry", "adjective"],
    ["hard", "hard", "adjective"],
    ["soft", "soft", "adjective"],
    ["smooth", "smooth", "adjective"],
    ["rough", "rough", "adjective"],
    ["sharp", "sharp", "adjective"],
    ["dull", "dull", "adjective"],
    ["strong", "strong", "adjective"],
    ["weak", "weak", "adjective"],
    ["old", "old", "adjective"],
    ["young", "young", "adjective"],
    ["new", "new", "adjective"],
    ["good", "good", "adjective"],
    ["bad", "bad", "adjective"],
    ["beautiful", "beautiful", "adjective"],
    ["ugly", "ugly", "adjective"],
    ["clean", "clean", "adjective"],
    ["dirty", "dirty", "adjective"],
    ["full", "full", "adjective"],
    ["empty", "empty", "adjective"],
    ["rich", "rich", "adjective"],
    ["poor", "poor", "adjective"],
    ["happy", "happy", "adjective"],
    ["sad", "sad", "adjective"],
    ["angry", "angry", "adjective"],
    ["afraid", "afraid", "adjective"],
    ["brave", "brave", "adjective"],
    ["kind", "kind", "adjective"],
    ["cruel", "cruel", "adjective"],
    ["wise", "wise", "adjective"],
    ["foolish", "foolish", "adjective"],
    ["alive", "alive", "adjective"],
    ["dead", "dead", "adjective"],
  ]),
  ...core("emotion_abstract", [
    ["joy", "joy", "noun"],
    ["sorrow", "sorrow", "noun"],
    ["anger", "anger", "noun"],
    ["fear_noun", "fear (noun)", "noun"],
    ["love_noun", "love (noun)", "noun"],
    ["hate_noun", "hate (noun)", "noun"],
    ["hope_noun", "hope (noun)", "noun"],
    ["despair", "despair", "noun"],
    ["pride", "pride", "noun"],
    ["shame", "shame", "noun"],
    ["jealousy", "jealousy", "noun"],
    ["courage", "courage", "noun"],
    ["peace", "peace", "noun"],
    ["war", "war", "noun"],
    ["freedom", "freedom", "noun"],
    ["justice", "justice", "noun"],
    ["truth", "truth", "noun"],
    ["lie_noun", "lie (falsehood)", "noun"],
    ["beauty", "beauty", "noun"],
    ["wisdom", "wisdom", "noun"],
    ["knowledge", "knowledge", "noun"],
    ["dream", "dream", "noun"],
    ["soul", "soul", "noun"],
    ["spirit", "spirit", "noun"],
    ["fate", "fate", "noun"],
    ["luck", "luck", "noun"],
    ["honor", "honor", "noun"],
    ["guilt", "guilt", "noun"],
    ["trust", "trust", "noun"],
    ["doubt", "doubt", "noun"],
    ["curiosity", "curiosity", "noun"],
    ["boredom", "boredom", "noun"],
    ["longing", "longing", "noun"],
    ["gratitude", "gratitude", "noun"],
    ["forgiveness", "forgiveness", "noun"],
  ]),
  ...core("social", [
    ["law", "law", "noun"],
    ["custom", "custom", "noun"],
    ["tradition", "tradition", "noun"],
    ["story", "story", "noun"],
    ["song", "song", "noun"],
    ["ritual", "ritual", "noun"],
    ["festival", "festival", "noun"],
    ["market", "market", "noun"],
    ["village", "village", "noun"],
    ["city", "city", "noun"],
    ["house", "house", "noun"],
    ["home", "home", "noun"],
    ["road", "road", "noun"],
    ["border", "border", "noun"],
    ["treaty", "treaty", "noun"],
    ["alliance", "alliance", "noun"],
    ["debt", "debt", "noun"],
    ["gift", "gift", "noun"],
    ["promise", "promise", "noun"],
    ["secret", "secret", "noun"],
  ]),
  ...core("objects", [
    ["tool", "tool", "noun"],
    ["knife", "knife", "noun"],
    ["axe", "axe", "noun"],
    ["spear", "spear", "noun"],
    ["bow_weapon", "bow (weapon)", "noun"],
    ["arrow", "arrow", "noun"],
    ["rope", "rope", "noun"],
    ["needle", "needle", "noun"],
    ["thread", "thread", "noun"],
    ["cloth", "cloth", "noun"],
    ["basket", "basket", "noun"],
    ["pot", "pot", "noun"],
    ["cup", "cup", "noun"],
    ["bowl", "bowl", "noun"],
    ["spoon", "spoon", "noun"],
    ["table", "table", "noun"],
    ["chair", "chair", "noun"],
    ["door", "door", "noun"],
    ["window", "window", "noun"],
    ["roof", "roof", "noun"],
    ["wall", "wall", "noun"],
    ["bridge", "bridge", "noun"],
    ["boat", "boat", "noun"],
    ["wheel", "wheel", "noun"],
    ["cart", "cart", "noun"],
    ["key", "key", "noun"],
    ["lock_noun", "lock (noun)", "noun"],
    ["lamp", "lamp", "noun"],
    ["candle", "candle", "noun"],
    ["book", "book", "noun"],
    ["letter", "letter", "noun"],
    ["coin", "coin", "noun"],
    ["money", "money", "noun"],
    ["bag", "bag", "noun"],
    ["blanket", "blanket", "noun"],
    ["bed", "bed", "noun"],
    ["fence", "fence", "noun"],
    ["ladder", "ladder", "noun"],
    ["mirror", "mirror", "noun"],
    ["clock", "clock", "noun"],
    ["shoe", "shoe", "noun"],
    ["cloak", "cloak", "noun"],
    ["belt", "belt", "noun"],
    ["ring_jewelry", "ring (jewelry)", "noun"],
    ["hat", "hat", "noun"],
  ]),
  ...core("colors_numbers", [
    ["red", "red", "adjective"],
    ["blue", "blue", "adjective"],
    ["green", "green", "adjective"],
    ["yellow", "yellow", "adjective"],
    ["black", "black", "adjective"],
    ["white", "white", "adjective"],
    ["gray", "gray", "adjective"],
    ["brown", "brown", "adjective"],
    ["one", "one", "numeral"],
    ["two", "two", "numeral"],
    ["three", "three", "numeral"],
    ["four", "four", "numeral"],
    ["five", "five", "numeral"],
    ["six", "six", "numeral"],
    ["seven", "seven", "numeral"],
    ["eight", "eight", "numeral"],
    ["nine", "nine", "numeral"],
    ["ten", "ten", "numeral"],
    ["hundred", "hundred", "numeral"],
    ["zero", "zero", "numeral"],
  ]),
];

export const FLEXIBLE_LIST: FlexibleConcept[] = [
  ...flexible("nautical", [
    ["ship", "ship", "noun"],
    ["sail", "sail", "noun"],
    ["oar", "oar", "noun"],
    ["anchor", "anchor", "noun"],
    ["harbor", "harbor", "noun"],
    ["tide", "tide", "noun"],
    ["wave_sea", "wave (sea)", "noun"],
    ["current_sea", "current (sea)", "noun"],
    ["reef", "reef", "noun"],
    ["fisherman", "fisherman", "noun"],
    ["net_fishing", "net (fishing)", "noun"],
    ["mast", "mast", "noun"],
    ["deck", "deck", "noun"],
    ["captain", "captain", "noun"],
    ["storm", "storm", "noun"],
    ["shore", "shore", "noun"],
    ["island", "island", "noun"],
    ["current_wind", "wind (as sailing force)", "noun"],
  ]),
  ...flexible("agricultural", [
    ["field", "field", "noun"],
    ["farm", "farm", "noun"],
    ["plow", "plow", "noun"],
    ["harvest", "harvest", "noun"],
    ["crop", "crop", "noun"],
    ["wheat", "wheat", "noun"],
    ["grain", "grain", "noun"],
    ["barley", "barley", "noun"],
    ["rice", "rice", "noun"],
    ["orchard", "orchard", "noun"],
    ["vineyard", "vineyard", "noun"],
    ["irrigation", "irrigation", "noun"],
    ["granary", "granary", "noun"],
    ["shepherd", "shepherd", "noun"],
    ["livestock", "livestock", "noun"],
    ["pasture", "pasture", "noun"],
    ["scythe", "scythe", "noun"],
    ["seedling", "seedling", "noun"],
  ]),
  ...flexible("martial", [
    ["sword", "sword", "noun"],
    ["shield", "shield", "noun"],
    ["armor", "armor", "noun"],
    ["fortress", "fortress", "noun"],
    ["siege", "siege", "noun"],
    ["banner", "banner", "noun"],
    ["army", "army", "noun"],
    ["soldier", "soldier", "noun"],
    ["battle", "battle", "noun"],
    ["wound", "wound", "noun"],
    ["victory", "victory", "noun"],
    ["defeat", "defeat", "noun"],
    ["ambush", "ambush", "noun"],
    ["cavalry", "cavalry", "noun"],
    ["garrison", "garrison", "noun"],
  ]),
  ...flexible("mercantile", [
    ["merchant", "merchant", "noun"],
    ["caravan", "caravan", "noun"],
    ["ledger", "ledger", "noun"],
    ["tariff", "tariff", "noun"],
    ["guild", "guild", "noun"],
    ["contract", "contract", "noun"],
    ["warehouse", "warehouse", "noun"],
    ["cargo", "cargo", "noun"],
    ["toll", "toll", "noun"],
    ["auction", "auction", "noun"],
    ["credit", "credit", "noun"],
    ["barter", "barter", "noun"],
    ["customer", "customer", "noun"],
    ["price", "price", "noun"],
    ["trade_noun", "trade (noun)", "noun"],
  ]),
  ...flexible("pastoral", [
    ["herd", "herd", "noun"],
    ["flock", "flock", "noun"],
    ["trap", "trap", "noun"],
    ["snare", "snare", "noun"],
    ["forage", "forage", "verb"],
    ["game_animal", "game (huntable animal)", "noun"],
    ["hide_pelt", "hide, pelt", "noun"],
    ["antler", "antler", "noun"],
    ["den", "den", "noun"],
    ["migration", "migration", "noun"],
    ["pack_wolves", "pack (of wolves)", "noun"],
    ["watering_hole", "watering hole", "noun"],
    ["campfire", "campfire", "noun"],
    ["nomad", "nomad", "noun"],
    ["trail", "trail", "noun"],
  ]),
  ...flexible("craft", [
    ["forge", "forge", "noun"],
    ["hammer", "hammer", "noun"],
    ["anvil", "anvil", "noun"],
    ["chisel", "chisel", "noun"],
    ["kiln", "kiln", "noun"],
    ["loom", "loom", "noun"],
    ["potter", "potter", "noun"],
    ["blacksmith", "blacksmith", "noun"],
    ["carpenter", "carpenter", "noun"],
    ["weaver", "weaver", "noun"],
    ["mason", "mason", "noun"],
    ["workshop", "workshop", "noun"],
    ["scaffold", "scaffold", "noun"],
    ["pigment", "pigment", "noun"],
    ["varnish", "varnish", "noun"],
  ]),
];

/**
 * Curated compound/idiomatic formations (Section 6.3) — real economical
 * vocabulary-building, not a generic "combine any two roots" mechanism.
 * A mix of transparent compounds (moonlight, sunflower) and non-literal
 * ones (shadow+foot = thief) so the lexicon doesn't feel like a dictionary
 * of independently invented words.
 */
export const COMPOUND_LIST: CompoundConcept[] = [
  { id: "glove", gloss: "glove (lit. hand-shoe)", pos: "noun", components: ["hand", "shoe"] },
  { id: "volcano", gloss: "volcano (lit. fire-mountain)", pos: "noun", components: ["fire", "mountain"] },
  { id: "passion", gloss: "passion (lit. fire of the heart)", pos: "noun", components: ["heart", "fire"] },
  {
    id: "hard_heartedness",
    gloss: "cruelty (lit. heart of stone)",
    pos: "noun",
    components: ["heart", "stone"],
  },
  {
    id: "swift_messenger",
    gloss: "swift messenger (lit. wind-horse)",
    pos: "noun",
    components: ["wind", "horse"],
  },
  { id: "eloquence", gloss: "eloquence (lit. tongue of fire)", pos: "noun", components: ["fire", "tongue"] },
  { id: "old_age", gloss: "old age (lit. white hair)", pos: "noun", components: ["white", "hair"] },
  { id: "strength", gloss: "strength (lit. hand of stone)", pos: "noun", components: ["stone", "hand"] },
  { id: "moonlight", gloss: "moonlight", pos: "noun", components: ["moon", "light"] },
  { id: "sunflower", gloss: "sunflower", pos: "noun", components: ["sun", "flower"] },
  { id: "canal", gloss: "canal (lit. water-road)", pos: "noun", components: ["water", "road"] },
  { id: "omen", gloss: "omen (lit. night-bird)", pos: "noun", components: ["night", "bird"] },
  {
    id: "divine_wrath",
    gloss: "divine wrath (lit. sky-fire)",
    pos: "noun",
    components: ["sky", "fire"],
  },
  { id: "vengeance", gloss: "vengeance (lit. blood-fire)", pos: "noun", components: ["blood", "fire"] },
  { id: "prophet", gloss: "prophet (lit. dream-eye)", pos: "noun", components: ["dream", "eye"] },
  { id: "grief", gloss: "grief (lit. salt-water)", pos: "noun", components: ["salt", "water"] },
  { id: "thief", gloss: "thief (lit. shadow-foot)", pos: "noun", components: ["shadow", "foot"] },
  { id: "generosity", gloss: "generosity (lit. gift-hand)", pos: "noun", components: ["gift", "hand"] },
  { id: "phoenix", gloss: "phoenix (lit. fire-bird)", pos: "noun", components: ["fire", "bird"] },
  { id: "hero", gloss: "chosen hero (lit. star-child)", pos: "noun", components: ["star", "child"] },
];
